### ISSUE TITLE
POST /on_assessment/details/{enrolmentKey} can be called multiple times

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#106]
There are a couple of problems. Documenting it for myself. Will figure out a fix sometime later.

1. `POST /on_assessment/details/{enrolmentKey}` can be called multiple times. There have been edge cases where a student answered a test and one of his friends again went on the same enrolment and updated the details which resulted in his details being updated. This needs to be fixed. Possible Fix: There could changes of stage every time some details are updated and validation can work on that basis.

2. Because of the same issue some records have a large number of mobile numbers because of constant attempts by the students. This needs to be fixed too.

**Comment by pralhad88** [comment]
It is done bhiya

**Comment by pralhad88** [comment]
This is the details that I discuss with Rishabh.

1. we have end that is related with student stage it's record students stage i.e. comletedTest, TestNotStarted etc. when student fill hes basic details i.e DOB, name, gender etc then we make one stage name as Basicdetails.

2. then change into front side in webapp/index.html when students stage is Basicdetails then it is not show the page relate with students basic details it directly goes on a next page. 

3. once student is save hes test answer and then again change hes stage from BasicDetails to CompletedTest.
 
for that purpose we need to change in front end as well as in backend.

**Comment by RishabhVerma** [comment]
Also currently `GET /on_assessment/validate_enrolment_key/{enrolmentKey}` returns the key status and the validity of the key. From now it will also return the stage of the student associated with the enrolment key. And this stage will be used by the frontend.

*Note: Please make sure all the stage transitions are recorded too.*

Yes you're right. But I think you missed all the stage changes as per the front-end.

Frontend has these 3 steps:

1. Student Enters Basic Details
2. Student Answers the Test
3. Students Enters Other Details

- After 1 the stage should change to `basicDetailsFilled`
- After 2 the stage should change to `completedTestWithoutAllDetails`
- After 3 the stage should change to `completedTestWithAllDetails`

And on the frontend the logic would be this

- If the stage is `enrolmentKeyGenerated` then show 1.
- If the stage is `basicDetailsFilled` then show 2 and skip 1.
- If stage is `completedTestWithAllDetails` then show 3 and skip 1 & 2.
