### ISSUE TITLE
typeOfTest Column should in enrolment_keys table and not students table

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#107]
Currently the students table has a `typeOfTest` column which tells if the test had been attempted by online or offline mode. Currently this is incorrect because this is not a student level data but a enrolment key level data.

So `typeOfTest` column needs to be removed from the `students` table and added to the `enrolment_keys` table.

**Comment by pralhad88** [comment]
Bhiya maine ye kar diya hai par new pull request ho nahi rahi, maine code ko push kiya hai issue-95 vali branch main.
