### ISSUE TITLE
React Panel for Partners to Track Their Students

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#108]
## How does it take place right now?

https://docs.google.com/spreadsheets/d/1WYvI-CQElAd55a7nz9U0UE1eQuDLArDXknWzDklk1Qk/edit#gid=486244847

Have a look at the `Stages` tab in the above google sheet.

## React Panel

A react panel should be there which the partners can use for tracking.

The URL for the panel will look something like this.

`http://join.navgurukul.org/partnerTracker/<partnerId>`

You can use the `partnerId` in the URL to ping an API to get the list of students. The JSON returned by the API is attached with this issue.

### `stageTransitions` 

This array in every student's record tells us about when the student transited from one stage to another. It'll be good if we can show this to the partners for the transparency. 

### Different Stages

There are multiple stages supported by Chanakya. A student can be at 1 of these stages.

```javascript
studentStages = [
	// related to the mcq test
	'enrolmentKeyGenerated',
	'completedTest',
	'testPassed',
	'testFailed',

	// related to incoming query calls
	'requestCallback',
	'pendingCallbackForQuery',
	'forReviewCallbackQueryResolved',
	'queryResolvedAfterCallback',

	// algebra interviews
	'pendingAlgebraInterview',
	'pendingAlgebraReInterview', // algebra re-interview
	'forReviewAlgebraInterviewDone',
	'algebraInterviewFail',
	'algebraInterviewWaitlisted',

	// english interviews
	'pendingEnglishInterview',
	'forReviewEnglishInterview',
	'englishInterviewFail',
	'englishInterviewWaitlisted',

	// culture fit interviews
	'pendingCultureFitInterview',
	'forReviewCultureFitInterviewDone',
	'cultureFitInterviewWaitlisted',
	'cultureFitInterviewFail',

	// parent conversations
	'pendingParentConversation',
	'parentConversationFail',

	// travel planning
	'pendingTravelPlanning',
	'finalisedTravelPlans',

	// probation etc. once when the student has joined navgurukul
	'probation',
	'finallyJoined',
	'droppedOut',
	'sentBackAfterProbation',

	// is not reachable
	'becameDisIntersested',

	// random stages for internal use
	'possibleDuplicate',
	'needAction',
	'demo',
	'disqualifiedUnreachable',
]
```

[students.json.zip](https://github.com/navgurukul/chanakya/files/3319799/students.json.zip)

**Comment by RishabhVerma** [comment]
## Clubbing of Stages

Here is a list of all possible stages but some of these are intermediate stages which don't need to be shown.

### Logical Interview Pending
1. 'testPassed'
2. 'pendingAlgebraInterview'
3. 'pendingAlgebraReInterview'
4. 'forReviewAlgebraInterviewDone'
5. 'algebraInterviewWaitlisted'

### English Interview Pending
1. 'pendingEnglishInterview'
2. 'forReviewEnglishInterview'
3. 'englishInterviewWaitlisted'


### Culture Fit Interview Pending
1. 'pendingCultureFitInterview',
2. 'forReviewCultureFitInterviewDone',
3. 'cultureFitInterviewWaitlisted',


### Show the Following Stages as It Is

Show these stages as it is. Just make them human readable names.

1. 'requestCallback'
2. 'pendingCallbackForQuery'
3. 'forReviewCallbackQueryResolved'
4. 'queryResolvedAfterCallback'
5. 'enrolmentKeyGenerated'
6. 'testFailed'
7. 'completedTest'
8. 'algebraInterviewFail'
9. 'englishInterviewFail'
10. 'cultureFitInterviewFail'
11. 'parentConversationFail'
12. 'droppedOut'
13. 'sentBackAfterProbation'
14. 'becameDisIntersested'
15. 'possibleDuplicate'
16. 'needAction'
17. 'demo'
18. 'disqualifiedUnreachable'

### Selected & Joining Awaited 
1. 'pendingParentConversation'
2. 'pendingTravelPlanning'
3. 'finalisedTravelPlans'

### Already Joined
1. 'probation',
2. 'finallyJoined'

## Stage Hover Helper Description

There should be an easy cue for the user which can help them that to understand that they can hover over any stage to understand what it means.

## Some Place where users can see the whole process

There should be a place which maybe opens a modal box to show the complete process. Currently you can copy past from the spreadsheet (https://docs.google.com/spreadsheets/d/1WYvI-CQElAd55a7nz9U0UE1eQuDLArDXknWzDklk1Qk/edit#gid=486244847) and I can keep on iterating on it as we go ahead.

## Filters

These are filters are quite important. If the city like filter is difficult to implement then you can implement standard text box filters. But for these fields specifically it's better to have a shitty filter than  not having a filter.

1. Set
2. Stage
3. Gender
4. State

## Add State
Currently the state of the student is not being shown. Some partners have presence in multiple states. Will be easy for them to add a state column.

**Comment by abhishekgupta92** [comment]
https://github.com/navgurukul/kalam/blob/master/src/data/stages.json
