### ISSUE TITLE
Generate Enrolment Key Route (/start/send_enrolment_key)

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#12]
## Description

Work on this route in `src/routes/start_flow.py`. This route will take the following parameters:

### GET Parameters

1. `mobile` (optional) 
2. `student_id` (optional)
3. `from_helpline` (required) will be true or false.

Out of `mobile` and `student_id`, one will be always be given. Otherwise throw an error.

If only `mobile` is given then create a new student entry and the required linked entries in the DB.

If only `student_id` is given then check if a valid enrolment key exists linked to that student. If it does then just send the message with an enrolment key otherwise generate a new one and then send a message.

The enrolment key generation logic should make sure that only one valid enrolment key per student should exist.

If `from_helpline` is true then an entry in the incoming calls table should be created.

## Return JSON
```json
{
    "sent": true,
    "generated": false
}
```

The value of `generated` will depend if a new enrolment key has been generated or an existing one has been re-sent.

**Comment by amarkrsinha1997** [comment]
Shall we add the exotel api in the same branch or we will add it later in some other branch

**Comment by amarkrsinha1997** [comment]
There needs to be something to handle the student when they are at rqc or interested call but haven't generated enrollment key for themselves there was no case here for that I have added condition to handle it in the branch issue_13

**Comment by RishabhVerma** [comment]
Why do we need to handle it? If we are given a `student_id` in the parameters that means we have to generate an enrolment key linked to the student with the given ID. How does it matter if the student is on RQC or any other stage?

**Comment by amarkrsinha1997** [comment]
I have reverted the merge and reset the commit back to the v2-boilerplate from where I started to write down the program
