### ISSUE TITLE
Validate Enrolment Key Route (/test/validate_enrolment_key)

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#14]
## What is it?
Given an enrolment key this route should validate if the enrolment key is valid.

## How it works?
GET Params will be:
1. `enrolment_key` (required)

A valid enrolment key is one which exists and has not expired. The expiry will be calculated from the `test_start_time` value of the `EnrolmentKey` model. The maximum allowed time elapsed from the `test_start_time` should be defined in config.

## Return JSON
```json
{
    "valid": false,
    "reason": "DOES_NOT_EXIST/EXPIRED"
}
```

The `reason` key will only exist if the enrolment key is not valid. Otherwise only `valid` key is enough.

**Comment by amarkrsinha1997** [comment]
Should the test be started when the key is being validated or in the route start-test?
I have written the logic to start the test here only removing the line to start the test in this route
