### ISSUE TITLE
Route (/test/personal_details)

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#20]
Complete this route. The student will submit his personal details (name, age etc.) on this route corresponding to his Enrolment Key which will save the data. Before starting the code please document the implementation on this issue. This will help me ensure if we are on the same page.

**Comment by amarkrsinha1997** [comment]
I will check if the enrollment key is valid or not 
if it will be valid I will add the data to the student related to the enrollment key
else  
will return a JSON
json
```
{
    success: false,
    reason:'ENROLLMENT NOT VALID /DOESN'T EXIST'
}
```

**Comment by amarkrsinha1997** [comment]
okay  got this part

**Comment by RishabhVerma** [comment]
@amarkrsinha1997 we will not create a new student as a student record would already exist in the DB. We would just add info on that student record.

**Comment by amarkrsinha1997** [comment]
in the personal Details we ask for mobile number also shouldn't we create a new student contact or shall we remove the mobile number from personal details? @RishabhVerma

**Comment by RishabhVerma** [comment]
Why will we create a new student? Then what is the point of attaching multiple student `StudentContact` instances with a student record.

**Comment by RishabhVerma** [comment]
What is the point of this code? 

```python
@api.doc(parser=enrolment_validation_parser)
    def get(self):

        args = self.enrolment_validation_parser.parse_args()
        enrollment_key = args.get('enrollment_key', None)
        enrollment = EnrolmentKey.query.filter_by(key=enrollment_key).first()

        # return the validaty of the key
```
This is written in `src/routes/test.py`

**Comment by RishabhVerma** [comment]
Secondly please document in the swagger docs that explains the meaning of all the possible responses for **POST `/test/personal_details`**

**Comment by amarkrsinha1997** [comment]
okay that was to validate the enrollment key before a person post needs to route to post the personal details is it wrong ?

**Comment by RishabhVerma** [comment]
But doesn't the POST request validate the enrollment key itself?

**Comment by amarkrsinha1997** [comment]
Yeah right, let me change it. I thought it would require to route towards the form to get the details.

**Comment by amarkrsinha1997** [comment]
I am confused in a part what happened is that I have updated a personal_details models which led to creating a new migrations file in that branch but after changing the question model in questions branch a new migration file would be created how will I merge both this migration file?
@RishabhVerma
