### ISSUE TITLE
Question Creation and Listing Endpoints

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#21]
We need to create questions and options in the DB which which helps us create & list questions in the DB. Here are the endpoints we would be using.

## POST /question/upload_file
This will take file as a parameter and upload the file on S3 and then generate a URL for the file which will be publicly accessible. We will later use this URL in the question options.

## POST /question
This will add a question into the DB. The input JSON might look something like this:
```json
{
    "text": {
        "en": "something",
        "hi": "something else"
    },
    "difficulty": "from the enum",
    "topic": "from the enum",
    "type": "from the enum"
    "options": [
        "option 1",
        "option 2",
        "option 3",
        "option 4"
    ],
    "answer": 2 
}
```
**`answer is the index of the option in the options list.`**

`QuestionOptions` model will be used to store the options.

## GET /questions
Return a list of all the questions.

## GET /questions/<id>
Returns a question with the given ID.

All these need to be created in a new file in routes called `questions.py`

**Comment by RishabhVerma** [comment]
@amarkrsinha1997 I am still waiting for your update on this one.

**Comment by amarkrsinha1997** [comment]
In the 
GET  / 
18 questions randomly should be retrieved and should be sent to as a JSON file 

GET/id /
will return the question from the  database in a JSON file if it exists

POST /
upload_file/
it will take a file as a parameter and will return the URL of the file which has been uploaded to S3.

question/
it will create a new question object and options based on how many options are provided in the params
and will save it all to the db. and  will return JSON file

**Comment by RishabhVerma** [comment]
All of this is correct. Just two clarifications:

1. You return the data as JSON and not a JSON file. 
2. There can be any number of questions. Not just 18.
3. You might have to change the privacy settings of the S3 buckets such that all the files uploaded are publicly visible.

**Comment by amarkrsinha1997** [comment]
Shall I use boto3?

**Comment by RishabhVerma** [comment]
Yes there should be a backref to get all options of a question. A user would want to see the questions and options together only. And yes all the questions have to stored in DB. Currently we have only 18 questions. But as the logic to generate  a question paper for the student is based on randomness on our question set. More questions would ensure more randomness and lesser cheating among students.

Also yes use boto3.

**Comment by RishabhVerma** [comment]
@amarkrsinha1997 also make sure to update the `requirements.txt` using `pip freeze > requirements.txt` whenever you use any new library in your code.

**Comment by amarkrsinha1997** [comment]
what is the answer for is to store the id of the answer_option or the index itself?

**Comment by RishabhVerma** [comment]
1. Which answer are you referring to?

2. Yes all languages need to be returned.

**Comment by amarkrsinha1997** [comment]
resolved point 1
