### ISSUE TITLE
Reduce the cut off to 16

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#22]
This for the code on `master` branch. Right now the cut off is 18. Only students with test scores more than 18 are not marked as `Entrance Test Failed`. This should be moved to 16. So anyone with 16 or more will pass the cut off

@amarkrsinha1997 This is priority. Isko pehle fix kar dena.

**Comment by amarkrsinha1997** [comment]
That means I have to add Passing marks of 16 right?

**Comment by amarkrsinha1997** [comment]
in config

**Comment by RishabhVerma** [comment]
I haven't seen the old code. Wherever that value is change it :P

**Comment by amarkrsinha1997** [comment]
if you check there already a logic I have set up in the config file and repos in the past
just need to add the variable MINIMUM_PASSING_SCORE=16 in other config file to make it working.

**Comment by RishabhVerma** [comment]
Awesome. Then can you please directly do it on Master and let me know here :)

**Comment by amarkrsinha1997** [comment]
I have pushed the code for this issue

**Comment by RishabhVerma** [comment]
Cool. Thanks. Assigning the issue to myself now.
