### ISSUE TITLE
Figure out namespaces in Swagger

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#25]
Currently all the issues in our Swagger documentation come under the same heading of default namespaces. There is some option of namespaces in Swagger that can help us group the routes in whatever way we want. Please look into that and make sure that we can group routes according to functionality.

<img width="1680" alt="screen shot 2018-08-27 at 12 40 31 pm" src="https://user-images.githubusercontent.com/933896/44645777-6b2d9b00-a9f6-11e8-9fcb-a6ae04de4fd6.png">

**Comment by amarkrsinha1997** [comment]
Implemented in dev-fixes branch
