### ISSUE TITLE
Offline Test Paper Generation Feature

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#30]
Our testing happens in two ways:

1. Students call the helpline and answer the test on the online platform.
2. Students answer the test offline at our partners.

For 1. we will be developing the online testing platform. For the 2. currently we have a google doc with Set A and Set B of the test. But we are reaching a stage where that is leading to a lot of cheating. We should have the ability to create unique tests every time one of our partners wants to get a test done. Our system should help us generate PDF of a test which we can send to the partner. Multiple sets should be generated. Here's the basic idea of the API:

## POST /test/offline_paper
This will take the following params:
1. `number_sets` (integer) the number of sets that need to be generated
2. `partner_name` (string) name of the partner for whom the test paper is being generated

This will return a link to a PDFs with the test papers. 

## GET /test/offline_paper
This will give out a list of all the test papers with the details.

## GET /test/offline_paper/<id>
This will give the detail of a single test paper with the given ID.

*Note: Remember, one test paper can have multiple sets.*

**Comment by RishabhVerma** [comment]
Everything seems perfect.

> partner name will be used to check if it is an online test or offline in is_online().

What do you mean by offline and online test? I don't get it.

**Comment by amarkrsinha1997** [comment]
We will have to even save the question generated for a student who gives the online test?
so how will we determine it is an online or offline test when we will try to get the whole set of paper generated by a different partner?

**Comment by RishabhVerma** [comment]
Oh yes we will have to. I missed it. Thanks for pointing out :)

**Comment by amarkrsinha1997** [comment]
`
 {'difficulty': 'Medium',
  'en_text': "<center><img src='https://image.ibb.co/dGqPyH/14.png' height='350px'></center> "
             '<br> Di gyi image me total kitne boxes hai?',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': 'B', 'hi_text': 'B'},
              {'correct': True, 'en_text': 'E', 'hi_text': 'E'},
              {'correct': False, 'en_text': 'C', 'hi_text': 'C'},
              {'correct': False, 'en_text': 'A', 'hi_text': 'A'}],
  'topic': 'Topic 1',
  'type': 'MQC'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/mGK6Cc/10.png' "
             "height='350px'></center><br/>"
             'Question mark ki jagah par sahi figure choose kijiye',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False,
               'en_text': 'https://image.ibb.co/mFr8Qx/10D.png',
               'hi_text': 'https://image.ibb.co/mFr8Qx/10D.png'},
              {'correct': False,
               'en_text': 'https://image.ibb.co/mf8oQx/10B.png',
               'hi_text': 'https://image.ibb.co/mf8oQx/10B.png'},
              {'correct': False,
               'en_text': 'https://image.ibb.co/fSrWdH/10C.png',
               'hi_text': 'https://image.ibb.co/fSrWdH/10C.png'},
              {'correct': True,
               'en_text': 'https://image.ibb.co/mCXF5x/10A.png',
               'hi_text': 'https://image.ibb.co/mCXF5x/10A.png'}],
  'topic': 'Topic 1',
  'type': 'MQC'},
`

**Comment by RishabhVerma** [comment]
The logic should be such that the HTML of every option and question text should be stored in HTML. Right now you are checking if the option text is URL. Your code should never be concerned what is in the text of options of questions. Everything will be HTML which we will depend on the browser to render instead of our code.

**Comment by amarkrsinha1997** [comment]
Cool changing it out right now!
