### ISSUE TITLE
Offline Test Paper Checking Feature

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#31]
Once we have generated an offline test paper we will also need to write the code to help us do the checking of the test papers. To get the papers checked we will be uploading the results in CSV in a format similar to this [spreadsheet](https://docs.google.com/spreadsheets/d/1VnwFt1r8LRdfOBIWFuEMlV6DdBJgqeOikqXC7VaRqLk/edit#gid=160551267).

## POST /test/offline_paper/<id>/add_results
This will help us add the results of the given test into the DB. The following params will be accepted:
1. `csv_url`: The URL which we got from `test/offline_paper/<id>/upload_results`

This will return an error in case there is an error with the CSV. Otherwise we will directly add the data into the DB.

## POST /test/offline_paper/<id>/upload_results
This will be a file upload URL which will be used to upload the file. Once we get the URL we will ping that URL to the `/test/offline_paper/<id>/add_results`

**Comment by amarkrsinha1997** [comment]
/test/offline_paper/<id>/upload_results
1. upload the file to s3 in a folder name offline_paper/<id> and return that link
2. should there be something to check if the CSV file is in the correct format?
3. should the link be saved in the database with any URL column any where for future reference or how will we reference it in future if needed?


/test/offline_paper/<id>/add_results
1.will get the file from the URL provided and will extract the data from the file.
2.Loop over each student data:
   a. get the set and the questions in question_order.
   b. extract all the question related to the set.
   c. save each attempt of the question_id, selected_option_id if exist, answer(Integer Answer)(loop over the set)
3. create a new student record for the student above.
4. how will we reference this attempts in future as there exists a column enrollment_key for online attempts how to do the same for offline?
5.should I create a partner_name in student table and more fields as per the csv in the student column?
6. How will I link this attempts with the student? 

@RishabhVerma

**Comment by amarkrsinha1997** [comment]
what's the use of id in upload_results? @RishabhVerma
