### ISSUE TITLE
Markdown Parser to Add Questions

### ISSUE THREAD

**Issue by amarkrsinha1997** [navgurukul/chanakya#34]
Create a script which can parse every question which is in MD format to HTML and save it to the database  with format that the Questions and QuestionOptions model required so we can directly render the HTML text in the front-end also upload every image to s3 and get a link for that image and save it to the database and 
update each question MD file with question_id which we will get after adding it to the database.

Notes:
When we run the script again the question which is already in the database should just get updated and rest question file which is not added should be added to the database.

@RishabhVerma

**Comment by amarkrsinha1997** [comment]
Question Parser Pseudocode: 


~ Find each all the MD files: 
~ Get the file data and also convert it to HTML using mistune markdown. 
~ check if the question is mcq or integer answer
	~ get the string of the hindi text and english text seperatly from the file data and convert it to html soup.
	
	~ update all the images path with s3 uploaded url in it with a class of center inside it and add the html string to the hi_text and en_text option.

	~ if it is mcq find all the tables in it using the soup to get the options of both the question in each file.
		~ loop over the cell.
		~ check if there is images in it update each images with s3 url. 
		~ mark 'correct' as False.
		~ save the soup as html string format in options list as same as the question model create function accept it.

		~ then get the correct answer index and update the answer as True.

	~ else just parse the questionChoiceMeta for the integer answer and create a option inside it in and mark 'correct' as True the same format the create question model accepts. 
	
	~ update the question dictionary with extra field like type topic and all.

	~ do this for the both questions choices.
	
~ check if the question is added or not added to the database if added then just update it(we can't ignore it because someone may make changes in it.)

~ update the question_pdf.html generator with the new way to add the data.

**Comment by RishabhVerma** [comment]
This seems okay.

**Comment by amarkrsinha1997** [comment]
While updating the question the image in the question and the options are getting
things to work like this

extract the image and upload it and then save its URL so later we can add it to database.
and the same logic goes for the update also what can I do to stop the image upload which is not changed

 reuploaded with a new link how can I stop that

**Comment by amarkrsinha1997** [comment]
I was thinking to store the id of the options also in the file or just update every option in that question with the data and randomly assigning the data in the option (means it will cause the change in the options data with another data that has been extracted from table). which one is better way or is there any other way also that we can do?

@RishabhVerma

**Comment by RishabhVerma** [comment]
> extract the image and upload it and then save its URL so later we can add it to database.
and the same logic goes for the update also what can I do to stop the image upload which is not changed

We don't need to stop it. This is over optimisation for now. Let more images be uploaded. The cost of checking if an image has changed or not is more than just uploading a new one.

**Comment by RishabhVerma** [comment]
> I was thinking to store the id of the options also in the file or just update every option in that question with the data and randomly assigning the data in the option (means it will cause the change in the options data with another data that has been extracted from table). which one is better way or is there any other way also that we can do?

Why can't options just be sequential? The sequence of options will make sure we always reference the same options. Does this make sense?

**Comment by amarkrsinha1997** [comment]
Yeah it make sense but the database doesn't always return the option in sequence it return it randomly how to make sure it is is being refrenced in a sequence?

**Comment by RishabhVerma** [comment]
Oh makes sense. You can then actually store the option IDs in the MD file. Makes sense.

**Comment by abhishekgupta92** [comment]
No option ids aren't needed in MD files. Will clarify this separately to
Amar in person tonight.

**Comment by amarkrsinha1997** [comment]
I just checked the options can be queried in a sequential order of how it had been added so we can go with the option you suggested @RishabhVerma

**Comment by RishabhVerma** [comment]
@abhishekgupta92 cool

**Comment by amarkrsinha1997** [comment]
I have created `common_text` field in questions tables and have `is_common` bool field to be marked True if it is common else False. is it a correct way to implement it or is there anything else to implement it?

**Comment by amarkrsinha1997** [comment]
Change the `question_obj` which is common in  `PUT_payload` and `GET_response` in the questions route as `is_common` field in `options` is not required in to be sent while updating questions where else `is_common` is required as response to differentiate that the options are not similar.
Do we have a better way to implement this?
changes need to be done after merging it with dev and also need to update the `question_pdf.html`
