### ISSUE TITLE
Complete Route (/test/extra_details) 

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#36]
All the extra details will be taken here. The details for now can be:

1. Caste (Dropdown)
2. Religon (Dropdown)
3. Monthly Family Income (Integer)
4. Total Family Members (Integer)
5. Family Member Income Details (Long Text)

**Comment by amarkrsinha1997** [comment]
The logic for the implementation.
```Post /test/extra_details```
will validate the enrollment key and before adding the data
the extra data will be updated to the student attached with the enrollment key

1. The Caste and Religion would be enums?
2. Family Member Income Details shall be db.Text?

after succesfully adding the data should a message be sent or just  json object with
```json
    "success":true,
    "error":false,

```

**Comment by amarkrsinha1997** [comment]
In validation we will only check if the enrollment key already exists or not rest all is in expired state or not means had given the test
