### ISSUE TITLE
Google Sheets Integration

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#42]
Currently there is no frontend to handle the calling from Chanakya. There needs to be a two way sync to do these things:

1. Whenever new data comes into Chanakya it should automatically be added into a Google Sheet.
2. Whenever some changes are made in the Google Sheet the changes should get reflected in the Chanakya DB. This would be help us (a) To send notifications like SMS etc. to the students. (b) Get a lot of analytics about the calling process etc. from the Chanakya server.

## Chanakya -> Google Sheets
These are the cases in which data would be added into the Google Sheet. The structure of data being added is also explained there only. The DB is a 3d structure with multiple tables but the excel sheet is mostly 1 single table in itself. So a lot of times we will have to massage data in a format good enough for excel. Example multiple things like Student Contacts, Student Details etc. are normalised across multiple tables but will all be under the same table when the data gets into a google sheet.

*Note 1:* When you're adding data in google sheets don't create a logic which is dependent on the column positions. There should be something which is dependent on column header names. The column positions can keep on changing as per needs.

*Note 2:* For StudentContact models, you can assume that there can be a maximum of two contacts per student and have two fields assigned in excel for that.

*Note 3:* Whenever you are dumping student data 

### Requested Callback
Normally the requested callbacks are linked to a student record. Currently in Excel there is no way we can signify this linking. So whenever a new requested callback will happen all the data of that student will be dumped in as single row of excel.

### After the student has answered the Test
When the student has answered the test all his data would be dumped again in a single row of excel.

## Google Sheets -> Chanakya
A script will run using Cron every x minutes to make sure that changes in Google Sheets are reflected in Chanakya. The ID column will be used to track the records.

Here are the things to do while sync will be happening:
1. Whenever stage is changed, make sure you create a Stage Transition

**Comment by amarkrsinha1997** [comment]
In the Requested callback, we have to create a new record or have to update an old record that the number is linked to.
