### ISSUE TITLE
Fixes on `dev`

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#46]
- [x] *`GET /online_test/start_test`* returns the correct key with every question which tells about the correct option. That's a security bug. Remove that.

- [x] Write a description for *`POST /online_test/extra_details`*

## Offline PDF Generation Fixes

- [x] There are empty lines after list markings in the PDF generated for offline test.

- [x] Use Open Sans. You can load the font from Google Fonts.

- [x] Don't Set <Number> format for the heading. You should instead use Set A, Set B etc. If there are two sets to be generated it would be A and B if 3 then A, B and C. The Set ID should be also be written in a bracket on the answer key page as that will help us upload correct data into the CSV.

- [x] Also include partner name in the heading of the question paper being generated.

- [x] In all the offline test endpoints it shouldn't be set_name as a JSON key but set_id

- [x] There should be a Set Name key also and set name key would have A, B C etc. You may have to make this change in the DB.

- [x] *` GET /offline_test/offline_paper/{id}/upload_results`* shouldn't have <id>. It is just meant for file upload.

- [x] Make a CSV according to the exact fields which are taken by Chanakya as input.

- [x] /offline_paper/<id>/add_results should be compute_results

- [x] Validation of every record of CSV should be done before. All the row numbers which are not valid should be given in the result. This will help the person understand what are the problems.

- [x] Figure out how folder specific installation of phantomJS can work instead of the system wide installation.

- [x] No Privilege & Verification call stage should be created. `ENTRANCE TEST ANSWERED` is the final stage that is there.

- [x] Figure out why PDF generation of the offline test is not working in Rishabh's computer. Do a new setup altogether to ensure there is no configuration stuff that is just is @amarkrsinha1997's laptop.

- [x] Set ID on the answer marking page of the Question Paper generated should in bracket and Set A/B etc. should also be written in the heading.

- [x] Remove the ID option for compute results URL.

- [x] When the CSV file is being submitted for computation of results also return the number of records added into the DB.

## Stage Transition

- [x] The student model should have a `change_stage` function instead of the StageTransition model. This is because whenever we are dealing stage transition it will be in the context of the student model.

## Google Sheets Integration

- [x] Only time data should be synced is when start_sync is called. Whenever start_sync is called then an option would be passed about the direction in which sync needs to happen.

## Overall

- [x] Every model should have a Created At time.

**Comment by RishabhVerma** [comment]
## Offline Question Paper Generation

- [ ] Figure out why PDF generation of the offline test is not working in Rishabh's computer. Do a new setup altogether to ensure there is no configuration stuff that is just is @amarkrsinha1997's laptop.

- [ ] Set ID on the answer marking page of the Question Paper generated should in bracket and Set A/B etc. should also be written in the heading.

**Comment by amarkrsinha1997** [comment]
Record the outgoing SMS for each student number

**Comment by amarkrsinha1997** [comment]
Send Sms to the student when they fail
