### ISSUE TITLE
Error in case of Invalid Enrolment Key

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#55]
Currently no error is shown if there is an invalid enrolment key.

**Comment by abhishekgupta92** [comment]
Uske baad kya flow hoga?
![Capture](https://user-images.githubusercontent.com/1681009/54787940-5b57fb80-4c53-11e9-852e-bf559d433418.PNG)

**Comment by RishabhVerma** [comment]
Just redirect to a new page where this message is displayed. Right now this is enough. 

Later on we can add a screen where the student can request the enrolment key from there itself.
