### ISSUE TITLE
Stage Transition Functionality

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#59]
Create a `stage_transitions` table in the DB with these columns:

1. `id` (auto increment)
2. `studentId` (foreign key ref to student)
3. `fromStage` (string with possible values from `CONSTANTS.studentStages`) (can be nullable)
4. `toStage` (string with possible values from `CONSTANTS.studentStages`)
5. `createdAt` (date/time)

# Pending Tasks

- [x] Create a table with migrations and make a model file with the name of `models/studentTransitions.js`
- [x] Make a relation with the name of `student` on the `studentTransitions` model from `student_transitions.studentId` to `students.id` This will be a belongs to on relation.
- [x] Make a relation with the name of `transitions` on `students` model from `students.id` to `student_transitions.studentId`. This will be a `Model.HasMany` kind of a relation.
- [x] Now when a student is being created using `studentService.create()` make a new stage transition using the `transitions` relationship where `fromStage` will be null and `toStage` will be the stage which is given in the stage parameter.
- [x] Also `assessmentService.patchStudentDetails` is used to change the stage. Add a condition in `patchStudentDetails` to see that whenever a `stage` key is given in the details, create a new transition for it also.
- [x] Send SMS to the users whenever a stage changes. Some stages might not require any SMS to be sent and some might. Currently SMS are using a variable in `constants.js` which stores the templates of all the SMS to be sent.

**Comment by RishabhVerma** [comment]
In the stage transitions migration do the following:

- [ ] When the stage transitions table is created, create transitions for the existing students on basis of these rules. 

1. For students on `enrolmentKeyGenerated` stage create a transition from `null` to `enrolmentKeyGenrated`. The `createdAt` time should be same as creation time of the enrolment key associated with that student.
2. For students on `completedTest` stage create a transition from `null` to `enrolmentKeyGenerated` whose `createdAt` will be the same as creation time of the enrolment key associated with that student. Then also created a transition from `enrolmentKeyGenerated` to `completedTest` where creation time will the `endTime` column of the associated enrolment key.
3. For `requestCallback` the transition should be from `null` to `requestCallback` with creation time of the transition being same as the creation time of the student.

**Comment by pralhad88** [comment]
updated the students current satage.

**Comment by RishabhVerma** [comment]
Don't close the issues until the code is merged in master.

**Comment by pralhad88** [comment]
Okay bhai

**Comment by RishabhVerma** [comment]
@amarkrsinha1997 All the stuff in this issue is done. You need to only integrate the SMS functionality. Though pralhad was doing it, but I guess he is unable to give time due to his sister's wedding.

**Comment by amarkrsinha1997** [comment]
done!
