### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#65]
Check the attached screenshots.

1. The timer should be static. Ideally time and next / previous question buttons should be sticky at the bottom and top respectively. Whenever keyboard the timer goes upwards and in longer questions previous buttons are not visible.

2. The text overflows outside the screen. Max width should be the screen width.

![](https://i.imgur.com/Btm6xX0.jpg)

![](https://i.imgur.com/SvSGIcU.jpg)

**Comment by abhishekgupta92** [comment]
css issues resolved, except sticky buttons. that requires much more work. will do soon.
