### ISSUE TITLE
Bug Fixes for Pralhad

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#72]
- [ ] In the offline PDF template on both the answers page & details page one column should be "WhatsApp" and another should be "Mobile". Both should have a proper box for the user to fill.

- [ ] Test out if the CSV flow in partnerships is working correctly or not.

- [ ] We have to remove the WhatsApp column in the `students` table. But before this we need to create a contact from the number in the `WhatsApp` column of every student if the given student doesn't have a contact with the same number listed. And if the student has a contact with the same number listed, change `isWhatsapp` to `true` for that contact. This code needs to be written in the migration.

- [ ] Test if all the APIs are working properly.

**Comment by RishabhVerma** [comment]
Do this and create a pull request from `dev` to `master`

**Comment by pralhad88** [comment]
I did all the task that are given by you.
