### ISSUE TITLE
Updating Stages from Google Sheet to Chanakya

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#78]
Currently the the data from Chanakya is dumped from the DB to Google Sheets. No changes from the google sheet are reflected back into the Chanakya DB. 

Whenever the `*Actual Stage*` column is updated for a record in the Google Sheet the stage should be updated for the student in Chanakya too.

## Stage Mapping
The values of stages in `Actual Stage` column are human values like "(For Review) Algebra Interview Done". To avoid errors we should be using camel case for stage values all across Chanakya and DB should just have those values. A mapping from human readable values to chankaya value of stages should exist somewhere which will take care of this. Example:

```javascript
{
    "(For Review) Algebra Interview Done": "forReviewAlgebraInterviewDone",
    "Algebra Interview Pending": "algebraInterviewPending"
}
```

## Reporting
Sometime the *Actual Stage* might have such values which Chanakya doesn't recognise and throws an error. In such cases no error should be thrown and all the records with the proper kind of values should still be synced. Only the records with wrong values should be highlighted and sent in an eMail report. The report will consist of 3 major things:

1. Total Number of Enrolment Key Records Added
2. Total Number of Incoming Call Records Added
3. All the records where the Actual Stage couldn't be updated. Here you can either include the Enrolment Key value for the enrolment key records and incomingCallId for the incoming call records.

**Comment by amarkrsinha1997** [comment]
done
