### ISSUE TITLE
Tracking Time since Stage Transition

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#81]
The google sheet should have a column which will show the time elapsed since the record entered the stage which is it's active stage. The reason for this is to track how much do records take to transition from one stage to another. This will help us improve our response times.

**Comment by amarkrsinha1997** [comment]
working on

**Comment by amarkrsinha1997** [comment]
done

**Comment by amarkrsinha1997** [comment]
gsheet coulmn name :*stageNotChangeSince*
