### ISSUE TITLE
Support Academic Detail Fields in CSV & Online Form

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#83]
We need to also record the following data of our students:

1. Class 10th Percentage
2. Maths Marks in 10th
3. Class 12th Percentage
4. Math marks in 12th

## Online Form
*Note: The API already supports these fields. Check it out.*

If the qualification is marked as less than 10th then none of the fields should show up. If the qualification is marked as Class 10th then the first 2 fields should show up.

If the qualification is marked as Class 12th then all the 4 fields should show up.

## CSV Upload
CSV should support all the 4 fields.

Both in the CSV & Online Form the fields should be optional.

## Nginx Config

Here is the Nginx config of Chanakya on the production. Basically all the requests on the frontend should be redirected to index.html in `webapp` folder. Our URLs generally comprise something like `http://join.navgurukul.org/k/<ENROLMENT_KEY>`. Basically then JS in index.html parses the enrolment key after `/k/` part of the URL.

```
server {
    listen 80;
    server_name join.navgurukul.org;
    
    root /home/chanakya/webapp;

    location / {
        try_files $uri /index.html;
    }

    location /static {
    }

    location /api/ {
        proxy_read_timeout 15s;
        proxy_connect_timeout 10s;
        proxy_pass http://localhost:3111/;
    }

}
```

**Comment by amarkrsinha1997** [comment]
done!
