### ISSUE TITLE
Blank Actual Stage during Two Way gSheet Sync doesn't mean an error

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#85]
Currently whenever the `Actual Stage` is blank right now Chanakya considers it as an error. That shouldn't be an error. That should mean that the record remains on whatever stage it has been without any changes.

An error will only be when the value in the `Actual Stage` column is not recognised by Chanakya.

**Comment by amarkrsinha1997** [comment]
done
