### ISSUE TITLE
Add a "No Cheating Promise" on Online Test Taking Platform & Offline Template

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#86]
There is quite some cheating that happens during the testing process, both online and offline. We cannot do anything to prevent the cheating but we should get a written confirmation from the students that they won't cheat and they are willing to go through any consequences if we figure out that they cheat. After the student enter their information & before the instructions page the a screen should be added with the following screen with a checkbox at the bottom.

## Read Carefully

A lot of students all across India answer the NavGurukul's test to go through the 1 year program and get high paying software engineering jobs. Though there is a great reward at the end, but you will have to do a lot of hard work to get that reward. We would love to teach every student irrespective of their educational qualifications but sadly we require some basic knowledge of certain things. We use this test to see if you have that basic knowledge.

Some students try to cheat and score well in the test but sadly are not able to do well during the program. All of them have to leave the course. 

If you are proceeding with the test please make sure you do it yourself without anyone's help. We will disqualify you from NavGurukul if we detect any form of cheating.

<I accept everything above> **this will be a button**

- [ ] Add this button in the online test. (@amarkrsinha1997)
- [ ] Add the same message in the offline test. (@RishabhVerma)

**Comment by amarkrsinha1997** [comment]
done!

**Comment by amarkrsinha1997** [comment]
Double check the html string.
