### ISSUE TITLE
Better gSheet Sync Report

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#87]
A few improvements need to be made in the gSheet sync report.

1. Make it a HTML template based report so it can be styled in anyway afterwards. You can add the template in the `templates` directory which exists under the `helpers` directory.
2. The errors should be a table. There should be two different tables. One for all the errors related to enrolment keys and the other for incoming call ids.
3. An empty Actual Stage shouldn't be treated as an error.

The enrolment key table in the report should have the following headers:
1. Enrolment Key
2. Errors in Syncing
3. gSheet Row #

Similarly the Incoming call table should have the following headers:
1. Incoming Call ID
3. Errors in Syncing
3. gSheet Row #

`The gSheet Row #` will have the row number of the record in the google sheet. This will make it easy for the person to detect the error and fix it faster.

**Comment by amarkrsinha1997** [comment]
Done!
