### ISSUE TITLE
Config file should be updated whenever questions are seeded into the DB.

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#90]
Whenever the questions are seeded into the DB by running `seedQuestions/index.js` the questions are seeded into the DB. Currently the config.json in `questions/config/config.json` takes care of maintaining the question buckets & choices.

But the config file is not updated with the IDs of the buckets & choices when the questions are seeded. This needs to happen whenever the seeding file is run.

The seeder file should also support a flag called `--noUpdateToConfig` which if given will make sure that config file is not updated. This can be used during development to play around.

Also update the `README.md` to document about `--noUpdateToConfig` added.

**Comment by pralhad88** [comment]
bhaiya can you explain me what to do in this task? I am not understood!

**Comment by RishabhVerma** [comment]
@pralhad88 Can you update the status of this issue?

**Comment by RishabhVerma** [comment]
You need to add the functionality for two more flags in the seeding script.

## `--updateConfigFile`

We might not want to update the config file always when we are seeding the the questions into the DB. This can happen for multiple reasons like running the seeding file on the development server etc.

## `--ignoreConfigBucketsAndChoices`
If this is given the IDs of the buckets and choices in the config file will be ignored and all of them will be added. We might want this functionality during development.

If the user is using both `--updateConfigFile` & `--ignoreConfigBucketsAndChoices` simultaneously he should be given a warning and asked to confirm.

Also please update the `README.md` with the documentation for these two flags.
