### ISSUE TITLE
Metrics for Tracking

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#95]
We need to track the following metrics at a daily level. Which means that a CRON should run at the end of every day to get all the numbers for the day.

1. Total Live Records in the System
2. Total Stale Records in the Pipeline
3. Total Students Joined
4. Total Number of Incoming Calls
5. Total Number of new Students who gave the test (From Partners)
6. Total Number of new Students who gave the test (From the Helpline)
6. Students who passed the test
7. Students who failed the test

A new table should be added which tracks all these metrics at a daily level. We can then generate weekly & monthly reports on basis of this.

Also add an API endpoint which gives the following reports for a given date range. If no date range is specified then give it for all days.

**Comment by RishabhVerma** [comment]
@amarkrsinha1997 @pralhad88 Would be best if you can get on a call with Varatha and define what all the metrics mean and document them right here so all of us are on the same page.

**Comment by amarkrsinha1997** [comment]
- **Live Record**: Students who have given the test & haven't been rejected or dropped out, comes under live records(**Still has a chance of getting selected**)
- **Stale Record**: stageNotChangeSince is greater than a week of any student.
- **Total Students Joined**: **stage: *Finally Joined*** Grand Total
- **Total Incoming Calls**: Per day.
- **5-6**: Total number of students who have completed the test today. (*testFailed*, *test passed*, blank)

**Comment by RishabhVerma** [comment]
1. Live Record: Can you include what stages are excluded out of this and what stages are included.
2. Stale Record: The stale-ness threshold should be controllable from the config file.

Also apart from this all these metrics will need to be recorded on a daily level. Here can be a possible database schema for this.

| id | metricName | value | date | createdAt |
|----|------------|-------|------|-----------|
|    |            |       |      |           |

**Comment by RishabhVerma** [comment]
Let me know if you have any issues in understanding the DB schema I proposed.

**Comment by amarkrsinha1997** [comment]
I am confused why are date and createdAt both in the table? when the metric would be recorded it will be recorded for the day it is being created?

**Comment by RishabhVerma** [comment]
That might not always be the case. Maybe we do some back calculation if we add a metric later on apart from these metrics. There can be other such cases too. That's why.

**Comment by amarkrsinha1997** [comment]
Can you give an example? I understand better with example.

**Comment by RishabhVerma** [comment]
Let's say we add another metric which calculates the number of students on an x stage every day. And what if you need to calculate this metric for the last 100 days. In that case createdAt will be different than date.

**Comment by amarkrsinha1997** [comment]
@RishabhVerma @pralhad88  I think we need to update the table as Varatha asked for recording male and female separately.

| id | metricName | value | gender | date | createdAt |
|----|------------|-------|------|-----------|---------|
|    |            |       |      |      |     |

**Comment by RishabhVerma** [comment]
## Live Record
`SELECT * FROM chanakya.students where stage in () and something about gender;`

## Stale Record
```sql
SELECT latestStages.*, stage_transitions.* 
	FROM (SELECT studentId, max(createdAt) as maxCreatedAt FROM chanakya.stage_transitions group by studentId) as latestStages 
    INNER JOIN stage_transitions 
    WHERE
		latestStages.maxCreatedAt=stage_transitions.createdAt
        AND
        latestStages.studentId = stage_transitions.studentId
        AND
        latestStages.maxCreatedAt < CURDATE() - INTERVAL 2 day
```

## Total Students on Probation
```sql
SELECT * FROM students WHERE stage = 'finallyJoined';
```

## Total Students Joined
```sql
SELECT * FROM students WHERE stage = 'probation';
```

## Total Number of Incoming Calls
Easy Query

## Total Number of new Students who gave the test (from partners)
where partner id is not null

## Total Number of new students who gave the test (from helpline)
where the partner is null

## Students who passed the test
easy

## Students who failed the test
easy
